### ISSUE TITLE
 Type of Cookie Popup 

### ISSUE THREAD

**Issue by Bartheus** [eigengrau-ch/strapi-plugin-cookie-manager#10]
More question then issue, but shouldn't be Cookie Popup a Single Type, not a Collection Type?  There is an option to manage only one Cookie Popup, not Popups, so the HTTP get request could be done as follows: 
```javascript
    return this.http.get<CookiePopup>(`${environment.apiUrl}/cookie-popup`);
```
and not like this, to avoid looping through the array :
```javascript
    return this.http.get<CookiePopup>(`${environment.apiUrl}/cookie-popups/1`);
```

**Comment by eigengrau-ch** [comment]
Hi @Bartheus, thanks for coming up with your question.

This is actually intended to be a working as Collection Type. The reason behind it, is a future update which enables the creation of multiple popup contents. For example in my use case, we have a initially visible popup which when cookies are customized by user action it will display another popup.
