### ISSUE TITLE
Improve installation documentation to prevent build error

### ISSUE THREAD

**Issue by neural-loop** [eigengrau-ch/strapi-plugin-cookie-manager#11]
```
● Webpack █████████████████████████ building (22%) 0/1 entries 5150/5188 dependencies 1132/1751 modules 362 active
 node_modules\react-select\dist\useStateManager-ce23061c.cjs.prod.js

ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/Loader' in 'C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie
-manager\node_modules\@strapi\design-system\dist\Button'
Did you mean 'Loader.js'?
BREAKING CHANGE: The request '@strapi/icons/Loader' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains 
'"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\Compilation.js:2016:28
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:798:13
    at eval (eval at create (C:\Users\mariale\WebstormProjects\ai-models\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:270:22
    at eval (eval at create (C:\Users\mariale\WebstormProjects\ai-models\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:434:22
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:116:11
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:670:25
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:855:8
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:975:5
resolve '@strapi/icons/Loader' in 'C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\But
ton'
  Parsed request is a module
  using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\package.json (rel
ative path: ./dist/Button)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\Button\node_modules doesn't exis
t or is not a directory
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\node_modules doesn't exist or is
 not a directory
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\node_modules doesn't exist or is not 
a directory
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\node_modules doesn't exist or is not a directory   
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules
        existing directory C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons
          using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\package.json (rel
ative path: .)
            using exports field: ./dist/Loader
              using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\package.json 
(relative path: ./dist/Loader)
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\dist\Loader doesn't exist
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules
        existing directory C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons
          using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\package.json (relative path: .)
            using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\package.json (relative path: ./Loader)
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\Loader doesn't exist
      C:\Users\mariale\WebstormProjects\node_modules doesn't exist or is not a directory
      C:\Users\mariale\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\admin\node_modules
        C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\admin\node_modules\@strapi\icons doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/Loader' in 'C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie
-manager\node_modules\@strapi\design-system\dist\Button'
Did you mean 'Loader.js'?
BREAKING CHANGE: The request '@strapi/icons/Loader' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains 
'"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\Compilation.js:2016:28
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:798:13
    at eval (eval at create (C:\Users\mariale\WebstormProjects\ai-models\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:270:22
    at eval (eval at create (C:\Users\mariale\WebstormProjects\ai-models\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:434:22
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:116:11
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:670:25
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:855:8
    at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:975:5
resolve '@strapi/icons/Loader' in 'C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\But
ton'
  Parsed request is a module
  using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\package.json (rel
ative path: ./dist/Button)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\Button\node_modules doesn't exis
t or is not a directory
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\node_modules doesn't exist or is
 not a directory
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\node_modules doesn't exist or is not 
a directory
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\node_modules doesn't exist or is not a directory   
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules
        existing directory C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons
          using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\package.json (rel
ative path: .)
            using exports field: ./dist/Loader
              using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\package.json 
(relative path: ./dist/Loader)
                Field 'browser' doesn't contain a valid alias configuration
                C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\dist\Loader doesn't exist
      C:\Users\mariale\WebstormProjects\ai-models\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules
        existing directory C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons
          using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\package.json (relative path: .)
            using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\package.json (relative path: ./Loader)
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\Loader doesn't exist
      C:\Users\mariale\WebstormProjects\node_modules doesn't exist or is not a directory
      C:\Users\mariale\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\admin\node_modules
        C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\admin\node_modules\@strapi\icons doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by mateoradman** [comment]
> ```
> ● Webpack █████████████████████████ building (22%) 0/1 entries 5150/5188 dependencies 1132/1751 modules 362 active
>  node_modules\react-select\dist\useStateManager-ce23061c.cjs.prod.js
> 
> ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/Loader' in 'C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie
> -manager\node_modules\@strapi\design-system\dist\Button'
> Did you mean 'Loader.js'?
> BREAKING CHANGE: The request '@strapi/icons/Loader' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains 
> '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\Compilation.js:2016:28
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:798:13
>     at eval (eval at create (C:\Users\mariale\WebstormProjects\ai-models\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:270:22
>     at eval (eval at create (C:\Users\mariale\WebstormProjects\ai-models\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:434:22
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:116:11
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:670:25
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:855:8
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:975:5
> resolve '@strapi/icons/Loader' in 'C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\But
> ton'
>   Parsed request is a module
>   using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\package.json (rel
> ative path: ./dist/Button)
>     Field 'browser' doesn't contain a valid alias configuration
>     resolve as module
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\Button\node_modules doesn't exis
> t or is not a directory
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\node_modules doesn't exist or is
>  not a directory
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\node_modules doesn't exist or is not 
> a directory
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\node_modules doesn't exist or is not a directory   
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\node_modules doesn't exist or is not a directory
>       looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules
>         existing directory C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons
>           using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\package.json (rel
> ative path: .)
>             using exports field: ./dist/Loader
>               using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\package.json 
> (relative path: ./dist/Loader)
>                 Field 'browser' doesn't contain a valid alias configuration
>                 C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\dist\Loader doesn't exist
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\node_modules doesn't exist or is not a directory
>       looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules
>         existing directory C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons
>           using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\package.json (relative path: .)
>             using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\package.json (relative path: ./Loader)
>               Field 'browser' doesn't contain a valid alias configuration
>               C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\Loader doesn't exist
>       C:\Users\mariale\WebstormProjects\node_modules doesn't exist or is not a directory
>       C:\Users\mariale\node_modules doesn't exist or is not a directory
>       C:\Users\node_modules doesn't exist or is not a directory
>       C:\node_modules doesn't exist or is not a directory
>       looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\admin\node_modules
>         C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\admin\node_modules\@strapi\icons doesn't exist
> ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/Loader' in 'C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie
> -manager\node_modules\@strapi\design-system\dist\Button'
> Did you mean 'Loader.js'?
> BREAKING CHANGE: The request '@strapi/icons/Loader' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains 
> '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\Compilation.js:2016:28
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:798:13
>     at eval (eval at create (C:\Users\mariale\WebstormProjects\ai-models\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:270:22
>     at eval (eval at create (C:\Users\mariale\WebstormProjects\ai-models\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:434:22
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:116:11
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:670:25
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:855:8
>     at C:\Users\mariale\WebstormProjects\ai-models\node_modules\webpack\lib\NormalModuleFactory.js:975:5
> resolve '@strapi/icons/Loader' in 'C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\But
> ton'
>   Parsed request is a module
>   using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\package.json (rel
> ative path: ./dist/Button)
>     Field 'browser' doesn't contain a valid alias configuration
>     resolve as module
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\Button\node_modules doesn't exis
> t or is not a directory
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\dist\node_modules doesn't exist or is
>  not a directory
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\design-system\node_modules doesn't exist or is not 
> a directory
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\node_modules doesn't exist or is not a directory   
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\node_modules doesn't exist or is not a directory
>       looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules
>         existing directory C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons
>           using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\package.json (rel
> ative path: .)
>             using exports field: ./dist/Loader
>               using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\package.json 
> (relative path: ./dist/Loader)
>                 Field 'browser' doesn't contain a valid alias configuration
>                 C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\node_modules\@strapi\icons\dist\Loader doesn't exist
>       C:\Users\mariale\WebstormProjects\ai-models\node_modules\node_modules doesn't exist or is not a directory
>       looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules
>         existing directory C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons
>           using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\package.json (relative path: .)
>             using description file: C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\package.json (relative path: ./Loader)
>               Field 'browser' doesn't contain a valid alias configuration
>               C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\icons\Loader doesn't exist
>       C:\Users\mariale\WebstormProjects\node_modules doesn't exist or is not a directory
>       C:\Users\mariale\node_modules doesn't exist or is not a directory
>       C:\Users\node_modules doesn't exist or is not a directory
>       C:\node_modules doesn't exist or is not a directory
>       looking for modules in C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\admin\node_modules
>         C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\admin\node_modules\@strapi\icons doesn't exist
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

I can reproduce the same problem after running 
```sh
yarn upgrade strapi-plugin-cookie-manager && yarn build && yarn develop
```
After downgrading, `yarn build` works again.

**Comment by eigengrau-ch** [comment]
Thanks @neural-loop and @mateoradman for reporting the issue.
I will take a look and dive into it the coming days. Hope you still are enjoying the plugin so far.

**Comment by eigengrau-ch** [comment]
Hi @mateoradman

I tried to reproduce the error, but could not. Would you share me the version of cookie-manager you are trying to upgrade from?

**Comment by neural-loop** [comment]
@eigengrau-ch I just tried it again and it worked. I bumped my version of strapi to the most recent.

**Comment by neural-loop** [comment]
```
TypeError: Cannot read properties of undefined (reading 'service')
    at Object.getLocales (C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\server\services\plugin.js:16:48)
    at Object.locales (C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\server\controllers\plugin.js:30:10)
    at dispatch (C:\Users\mariale\WebstormProjects\ai-models\node_modules\koa-compose\index.js:42:32)
    at returnBodyMiddleware (C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:24)
    at dispatch (C:\Users\mariale\WebstormProjects\ai-models\node_modules\koa-compose\index.js:42:32)
    at policiesMiddleware (C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\strapi\lib\services\server\policy.js:24:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I did see this when I went to open the page. Haven't investigated yet but wanted to post the message in case it means something

**Comment by eigengrau-ch** [comment]
Hi @neural-loop

Did you manage to build now?

Regarding the first error, did the plugin generated the content types with `strapi develop` for you? You should have those folders within `/src/api/` for `cookie` and `cookie-category`:

```
- content-types
- controllers
- routes
- services
```

In case of your second error, it is because you seem to not import the `createCoreService` function like this:

```js
const { createCoreService } = require('@strapi/strapi').factories;
```

**Comment by neural-loop** [comment]
The version before was 4.5.1. I'm going to try your suggestions

**Comment by neural-loop** [comment]
1: yarn add strapi-plugin-cookie-manager 
2:  strapi build 
3. strapi develop cookie - cookie-category - cookie-popup created
4. visit localhost:1337 site and click cookie manager

```

[2022-12-03 22:30:42.337] http: GET /cookie-manager/config (10 ms) 200
[2022-12-03 22:30:42.347] http: GET /cookie-manager/cookie-category/find (10 ms) 200
[2022-12-03 22:30:42.357] error: Cannot read properties of undefined (reading 'service')
TypeError: Cannot read properties of undefined (reading 'service')
    at Object.getLocales (C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\server\services\plugin.js:16:48)
    at Object.locales (C:\Users\mariale\WebstormProjects\ai-models\node_modules\strapi-plugin-cookie-manager\server\controllers\plugin.js:30:10)
    at dispatch (C:\Users\mariale\WebstormProjects\ai-models\node_modules\koa-compose\index.js:42:32)
    at returnBodyMiddleware (C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:24)
    at dispatch (C:\Users\mariale\WebstormProjects\ai-models\node_modules\koa-compose\index.js:42:32)
    at policiesMiddleware (C:\Users\mariale\WebstormProjects\ai-models\node_modules\@strapi\strapi\lib\services\server\policy.js:24:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-12-03 22:30:42.366] http: GET /cookie-manager/cookie/find (8 ms) 200
[2022-12-03 22:30:42.380] http: GET /cookie-manager/cookie-popup/find (9 ms) 200

```

**Comment by skyclb** [comment]
@neural-loop thanks for your step by step instruction. I might have a guess, do you have the strapi i18n plugin installed? Because it looks like the service to find your locales can not be found.

**Comment by neural-loop** [comment]
I don't.. let me turn that on

**Comment by neural-loop** [comment]
I didn't think about the i18n stuff because often times, even if a plugin supports i18n, it usually works without it, just lacking the features. I see that it says in the docs that i18n is enabled by default, I didn't think about it too much as I thought it'd see that I don't have it installed and wouldn't make a difference.  Thanks much for the assistance

**Comment by eigengrau-ch** [comment]
The Documentation has been enhanced to hint the importance of the `i18n plugin` already at the installation of the plugin.
