### ISSUE TITLE
Error: Could not load content type

### ISSUE THREAD

**Issue by RBede** [eigengrau-ch/strapi-plugin-cookie-manager#20]
Hi.

1. Install latest strapi via quick cammand in get started : `yarn create strapi-app my-project --quickstart`
2. Install cookie-manager plugin : `yarn add strapi-plugin-cookie-manager`
3. Build : `yarn build `
4. Start in developement mod (`yarn develop`) or normal (`yarn start`)

Error : 
```
Error: Could not load content type found at /Users/rbouillard/Documents/www/strapi/src/api/cookie-popup/content-types
    at loadContentTypes (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/core/loaders/apis.js:120:13)
    at async Promise.all (index 7)
    at async loadAPI (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/core/loaders/apis.js:73:5)
    at async module.exports [as loadAPIs] (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/core/loaders/apis.js:36:17)
    at async Strapi.loadAPIs (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/Strapi.js:353:5)
    at async Promise.all (index 4)
    at async Strapi.register (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/Strapi.js:381:5)
    at async Strapi.load (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/Strapi.js:491:5)
    at async workerProcess (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/commands/actions/develop/action.js:110:26)
```

I don't known if I've missed something but according to https://market.strapi.io/plugins/strapi-plugin-cookie-manager i've see no more config to set up the plugin.

**Comment by schlotterich** [comment]
Same problem for me. I tried it with npm and yarn: 

```
$ strapi develop
SyntaxError: /Users/schlotterich/WebProjects/valsight/backend/src/api/cookie-popup/content-types/cookie-popup/schema.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object._readFile (/Users/schlotterich/WebProjects/valsight/backend/node_modules/jsonfile/index.js:25:16)
    at async loadDir (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/core/loaders/apis.js:144:32)
    at async loadContentTypes (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/core/loaders/apis.js:117:25)
    at async Promise.all (index 7)
    at async loadAPI (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/core/loaders/apis.js:73:5)
    at async module.exports [as loadAPIs] (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/core/loaders/apis.js:36:17)
    at async Strapi.loadAPIs (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/Strapi.js:353:5)
    at async Promise.all (index 4)
    at async Strapi.register (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/Strapi.js:381:5)
✨  Done in 2.29s.
```

If I run it with yarn, the schema.json is empty. With npm it has an empty draftAndPublish:

```
{
  "kind": "collectionType",
  "collectionName": "cookie_popups",
  "info": {
    "singularName": "cookie-popup",
    "pluralName": "cookie-popups",
    "displayName": "Cookie Popups"
  },
  "options": {
    "draftAndPublish": ,
    "comment": ""
  },
  "attributes": {}
}
```

**Comment by zaychoer** [comment]
I think u should setup your api services, based on [documentations](https://market.strapi.io/plugins/strapi-plugin-cookie-manager) 

`./src/api/cookie/services/cookie.js`
```
module.exports = createCoreService('api::cookie.cookie', ({ strapi }) => ({
  async find(params) {
    const { pagination } = await super.find(params);
    const results = await strapi.entityService.findMany("api::cookie.cookie", Object.assign(params, {
      populate: { category: true }
    }))

    return { results, pagination };
  },
}));
```
`./src/api/cookie-category/services/cookie-category.js`
```
module.exports = createCoreService('api::cookie-category.cookie-category', ({ strapi }) => ({
  async find(params) {
    const { pagination } = await super.find(params);
    const results = await strapi.entityService.findMany("api::cookie-category.cookie-category", Object.assign(params, {
      populate: { cookies: true }
    }))

    return { results, pagination }
  },
}));
```

**Comment by eigengrau-ch** [comment]
Thank you guys for reporting! I will look into it as soon as possible.

**Comment by eigengrau-ch** [comment]
> Same problem for me. I tried it with npm and yarn:
> 
> ```
> $ strapi develop
> SyntaxError: /Users/schlotterich/WebProjects/valsight/backend/src/api/cookie-popup/content-types/cookie-popup/schema.json: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at Object._readFile (/Users/schlotterich/WebProjects/valsight/backend/node_modules/jsonfile/index.js:25:16)
>     at async loadDir (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/core/loaders/apis.js:144:32)
>     at async loadContentTypes (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/core/loaders/apis.js:117:25)
>     at async Promise.all (index 7)
>     at async loadAPI (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/core/loaders/apis.js:73:5)
>     at async module.exports [as loadAPIs] (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/core/loaders/apis.js:36:17)
>     at async Strapi.loadAPIs (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/Strapi.js:353:5)
>     at async Promise.all (index 4)
>     at async Strapi.register (/Users/schlotterich/WebProjects/valsight/backend/node_modules/@strapi/strapi/lib/Strapi.js:381:5)
> ✨  Done in 2.29s.
> ```
> 
> If I run it with yarn, the schema.json is empty. With npm it has an empty draftAndPublish:
> 
> ```
> {
>   "kind": "collectionType",
>   "collectionName": "cookie_popups",
>   "info": {
>     "singularName": "cookie-popup",
>     "pluralName": "cookie-popups",
>     "displayName": "Cookie Popups"
>   },
>   "options": {
>     "draftAndPublish": ,
>     "comment": ""
>   },
>   "attributes": {}
> }
> ```

Hi @schlotterich, this can happen on rare equations. If you haven't filled any content so far, you could just delete the cookie content types generated and regenerate them again with `yarn develop`. Just make sure strapi is not running then deleting.

If you have already filled content, then you probably need to add the proper content type schemas manually. Just replace your `schema.json` for each content type with following ones here: https://github.com/eigengrau-ch/strapi-plugin-cookie-manager/tree/main/server/content-types

Hope this helps

**Comment by eigengrau-ch** [comment]
> Hi.
> 
> 1. Install latest strapi via quick cammand in get started : `yarn create strapi-app my-project --quickstart`
> 2. Install cookie-manager plugin : `yarn add strapi-plugin-cookie-manager`
> 3. Build : `yarn build `
> 4. Start in developement mod (`yarn develop`) or normal (`yarn start`)
> 
> Error :
> 
> ```
> Error: Could not load content type found at /Users/rbouillard/Documents/www/strapi/src/api/cookie-popup/content-types
>     at loadContentTypes (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/core/loaders/apis.js:120:13)
>     at async Promise.all (index 7)
>     at async loadAPI (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/core/loaders/apis.js:73:5)
>     at async module.exports [as loadAPIs] (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/core/loaders/apis.js:36:17)
>     at async Strapi.loadAPIs (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/Strapi.js:353:5)
>     at async Promise.all (index 4)
>     at async Strapi.register (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/Strapi.js:381:5)
>     at async Strapi.load (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/Strapi.js:491:5)
>     at async workerProcess (/Users/rbouillard/Documents/www/strapi/node_modules/@strapi/strapi/lib/commands/actions/develop/action.js:110:26)
> ```
> 
> I don't known if I've missed something but according to https://market.strapi.io/plugins/strapi-plugin-cookie-manager i've see no more config to set up the plugin.

Hi @RBede, unfortunately I was unable to reproduce this error following your steps. Could you provide more information on the strapi version you are were using?

**Comment by eigengrau-ch** [comment]
Closed, since there has not been any more response
