### ISSUE TITLE
Getting issue after updating node.js to >=14.19.1 <=20.x.x

### ISSUE THREAD

**Issue by NdekoCode** [eigengrau-ch/strapi-plugin-cookie-manager#25]
Steps to take to reproduce the problem:

1. Have node.js greater than version 18 on your machine
2. Start installing the dependencies from the beginning

![Screenshoot](https://github.com/eigengrau-ch/strapi-plugin-cookie-manager/assets/85836702/4cde3c50-503d-4b1f-9745-1db89073ebd0)

Environment details :
Strapi version: 4.15.0
Cookie-manager version: 1.2.2
OS: Ubuntu 23

Have I forgotten something or is there a problem with the plugin?

**Comment by TheMrKiko** [comment]
Same problem for me. Some fix like https://github.com/vivmagarwal/strapi-plugin-custom-api-builder/pull/24/files this should be done

**Comment by SalahAdDin** [comment]
@eigengrau-ch Are you still maintaining this package?
