### ISSUE TITLE
Cookie description max length is too small

### ISSUE THREAD

**Issue by yarikwest** [eigengrau-ch/strapi-plugin-cookie-manager#7]
Hello,
there are some possibility to change max length for description for cookie and cookie-category. For me 250 chars isn't enough.
Thanks

**Comment by eigengrau-ch** [comment]
Hi @yarikwest, thanks for reaching out with your request. We could increase it, but then the description inside the accordion would start look very bad.

Another option would be to use `patch-package` in order to adjust the max length of the description validation. You can find the responsible validation rule here: admin/src/components/CategoryModal/validation.js:L30

If you think this is a necessary change, feel free to share me some arguments.

**Comment by Bartheus** [comment]
I think as well that max length of description should be increased on cookie / cookie category and popup. These days not every cookie popup message looks like this "Please accept our cookie policy...".   Btw. which accordion u mean actually?

**Comment by eigengrau-ch** [comment]
Hi @Bartheus, thank you too for sharing your feedback here. Currently were you manage categories and cookies is build as accordion. I did some investigation and we could increase it, i only need to add a truncation so to prevent the user interface from looking worse.

How many characters would you guys suggest? Would 500 be enough?

**Comment by Bartheus** [comment]
So I personally like this plugin and my Cookie Policy is 1107 characters long. I know it's much but my client want to have this all important information shown. So my suggestion is 2000 characters.

**Comment by eigengrau-ch** [comment]
We are happy that you are enjoying the plugin and thank you @Bartheus for giving us your inputs, they are really helpful. I did some investigation and changing the fields in Strapi to 2000 characters will not be a issue at all. I will consider this change for the next release.

**Comment by eigengrau-ch** [comment]
Hi @Bartheus, hope you are doing good? Sorry that there has not been an update yet. I was very busy with client projects which prevented me from doing further changes on the plugin. I am looking forward to publish the next version by end of this month which will fix this issue.

Thank you very much for your patience!

**Comment by eigengrau-ch** [comment]
Dear @Bartheus, the field lengths has been increased in the latest release 1.0.10. I hope the new length is long enough, if not feel free to create a new issue again.
